version: '3'
volumes:
 web:
services:

  haproxy:
    build: ./haproxy
    ports:
      - "8486:80"
      - "8487:8484"
    depends_on:
      - apache1
      - apache2
  
  apache1:
    hostname: apache1
    build: ./apache
    depends_on:
      - db
    volumes:
      - web
    expose:
      - "80"

  apache2:
    hostname: apache2
    build: ./apache
    depends_on:
      - db
    volumes:
      - web
    expose:
      - "80"

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: bolson
        MYSQL_DATABASE: prueba
        MYSQL_USER: frodo
        MYSQL_PASSWORD: bolson
    ports:
        - "9906:3306"
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8085:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
      - db
